{
  "cells": [
    {
      "cell_type": "code",
      "source": [
        "from azureml.core import Workspace, Datastore, Experiment, Environment\n",
        "from azureml.core.runconfig import RunConfiguration\n",
        "from azureml.pipeline.steps import PythonScriptStep\n",
        "from azureml.pipeline.core import Pipeline"
      ],
      "outputs": [],
      "execution_count": 2,
      "metadata": {
        "gather": {
          "logged": 1723924564702
        }
      }
    },
    {
      "cell_type": "code",
      "source": [
        "pip install azureml-pipeline"
      ],
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": "Requirement already satisfied: azureml-pipeline in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (1.57.0)\nRequirement already satisfied: azureml-pipeline-core~=1.57.0 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from azureml-pipeline) (1.57.0)\nRequirement already satisfied: azureml-pipeline-steps~=1.57.0 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from azureml-pipeline) (1.57.0)\nRequirement already satisfied: azureml-core~=1.57.0 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from azureml-pipeline-core~=1.57.0->azureml-pipeline) (1.57.0)\nRequirement already satisfied: azureml-train-core~=1.57.0 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from azureml-pipeline-steps~=1.57.0->azureml-pipeline) (1.57.0)\nRequirement already satisfied: azureml-train-automl-client~=1.57.0 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from azureml-pipeline-steps~=1.57.0->azureml-pipeline) (1.57.0)\nRequirement already satisfied: pytz in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from azureml-core~=1.57.0->azureml-pipeline-core~=1.57.0->azureml-pipeline) (2024.1)\nRequirement already satisfied: backports.tempfile in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from azureml-core~=1.57.0->azureml-pipeline-core~=1.57.0->azureml-pipeline) (1.0)\nRequirement already satisfied: pathspec<1.0.0 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from azureml-core~=1.57.0->azureml-pipeline-core~=1.57.0->azureml-pipeline) (0.12.1)\nRequirement already satisfied: requests<3.0.0,>=2.19.1 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from requests[socks]<3.0.0,>=2.19.1->azureml-core~=1.57.0->azureml-pipeline-core~=1.57.0->azureml-pipeline) (2.32.3)\nRequirement already satisfied: msal<2.0.0,>=1.15.0 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from azureml-core~=1.57.0->azureml-pipeline-core~=1.57.0->azureml-pipeline) (1.28.0)\nRequirement already satisfied: msal-extensions<=2.0.0,>=0.3.0 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from azureml-core~=1.57.0->azureml-pipeline-core~=1.57.0->azureml-pipeline) (1.1.0)\nRequirement already satisfied: knack<0.12.0 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from azureml-core~=1.57.0->azureml-pipeline-core~=1.57.0->azureml-pipeline) (0.11.0)\nRequirement already satisfied: azure-core<2.0.0 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from azureml-core~=1.57.0->azureml-pipeline-core~=1.57.0->azureml-pipeline) (1.30.2)\nRequirement already satisfied: pkginfo in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from azureml-core~=1.57.0->azureml-pipeline-core~=1.57.0->azureml-pipeline) (1.11.1)\nRequirement already satisfied: argcomplete<4 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from azureml-core~=1.57.0->azureml-pipeline-core~=1.57.0->azureml-pipeline) (3.3.0)\nRequirement already satisfied: humanfriendly<11.0,>=4.7 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from azureml-core~=1.57.0->azureml-pipeline-core~=1.57.0->azureml-pipeline) (10.0)\nRequirement already satisfied: paramiko<4.0.0,>=2.0.8 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from azureml-core~=1.57.0->azureml-pipeline-core~=1.57.0->azureml-pipeline) (3.4.0)\nRequirement already satisfied: azure-mgmt-resource<=24.0.0,>=15.0.0 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from azureml-core~=1.57.0->azureml-pipeline-core~=1.57.0->azureml-pipeline) (23.1.1)\nRequirement already satisfied: azure-mgmt-containerregistry<11,>=8.2.0 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from azureml-core~=1.57.0->azureml-pipeline-core~=1.57.0->azureml-pipeline) (10.3.0)\nRequirement already satisfied: azure-mgmt-storage<=22.0.0,>=16.0.0 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from azureml-core~=1.57.0->azureml-pipeline-core~=1.57.0->azureml-pipeline) (21.1.0)\nRequirement already satisfied: azure-mgmt-keyvault<11.0.0,>=0.40.0 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from azureml-core~=1.57.0->azureml-pipeline-core~=1.57.0->azureml-pipeline) (10.3.0)\nRequirement already satisfied: azure-mgmt-authorization<5,>=0.40.0 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from azureml-core~=1.57.0->azureml-pipeline-core~=1.57.0->azureml-pipeline) (4.0.0)\nRequirement already satisfied: azure-mgmt-network<=26.0.0 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from azureml-core~=1.57.0->azureml-pipeline-core~=1.57.0->azureml-pipeline) (25.4.0)\nRequirement already satisfied: azure-graphrbac<1.0.0,>=0.40.0 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from azureml-core~=1.57.0->azureml-pipeline-core~=1.57.0->azureml-pipeline) (0.61.1)\nRequirement already satisfied: azure-common<2.0.0,>=1.1.12 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from azureml-core~=1.57.0->azureml-pipeline-core~=1.57.0->azureml-pipeline) (1.1.28)\nRequirement already satisfied: msrest<=0.7.1,>=0.5.1 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from azureml-core~=1.57.0->azureml-pipeline-core~=1.57.0->azureml-pipeline) (0.7.1)\nRequirement already satisfied: msrestazure<=0.7,>=0.4.33 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from azureml-core~=1.57.0->azureml-pipeline-core~=1.57.0->azureml-pipeline) (0.6.4)\nRequirement already satisfied: urllib3<3.0.0,>1.26.17 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from azureml-core~=1.57.0->azureml-pipeline-core~=1.57.0->azureml-pipeline) (2.2.1)\nRequirement already satisfied: packaging<=25.0,>=20.0 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from azureml-core~=1.57.0->azureml-pipeline-core~=1.57.0->azureml-pipeline) (24.0)\nRequirement already satisfied: python-dateutil<3.0.0,>=2.7.3 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from azureml-core~=1.57.0->azureml-pipeline-core~=1.57.0->azureml-pipeline) (2.9.0)\nRequirement already satisfied: ndg-httpsclient<=0.5.1 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from azureml-core~=1.57.0->azureml-pipeline-core~=1.57.0->azureml-pipeline) (0.5.1)\nRequirement already satisfied: SecretStorage<4.0.0 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from azureml-core~=1.57.0->azureml-pipeline-core~=1.57.0->azureml-pipeline) (3.3.3)\nRequirement already satisfied: jsonpickle<4.0.0 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from azureml-core~=1.57.0->azureml-pipeline-core~=1.57.0->azureml-pipeline) (3.2.1)\nRequirement already satisfied: contextlib2<22.0.0 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from azureml-core~=1.57.0->azureml-pipeline-core~=1.57.0->azureml-pipeline) (21.6.0)\nRequirement already satisfied: docker<8.0.0 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from azureml-core~=1.57.0->azureml-pipeline-core~=1.57.0->azureml-pipeline) (7.1.0)\nRequirement already satisfied: PyJWT<3.0.0 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from azureml-core~=1.57.0->azureml-pipeline-core~=1.57.0->azureml-pipeline) (2.8.0)\nRequirement already satisfied: adal<=1.2.7,>=1.2.0 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from azureml-core~=1.57.0->azureml-pipeline-core~=1.57.0->azureml-pipeline) (1.2.7)\nRequirement already satisfied: pyopenssl<25.0.0 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from azureml-core~=1.57.0->azureml-pipeline-core~=1.57.0->azureml-pipeline) (24.1.0)\nRequirement already satisfied: jmespath<2.0.0 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from azureml-core~=1.57.0->azureml-pipeline-core~=1.57.0->azureml-pipeline) (1.0.1)\nRequirement already satisfied: azureml-automl-core~=1.57.0 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from azureml-train-automl-client~=1.57.0->azureml-pipeline-steps~=1.57.0->azureml-pipeline) (1.57.0)\nRequirement already satisfied: azureml-dataset-runtime~=1.57.0 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from azureml-train-automl-client~=1.57.0->azureml-pipeline-steps~=1.57.0->azureml-pipeline) (1.57.0)\nRequirement already satisfied: azureml-telemetry~=1.57.0 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from azureml-train-automl-client~=1.57.0->azureml-pipeline-steps~=1.57.0->azureml-pipeline) (1.57.0)\nRequirement already satisfied: azureml-train-restclients-hyperdrive~=1.57.0 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from azureml-train-core~=1.57.0->azureml-pipeline-steps~=1.57.0->azureml-pipeline) (1.57.0)\nRequirement already satisfied: cryptography>=1.1.0 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from adal<=1.2.7,>=1.2.0->azureml-core~=1.57.0->azureml-pipeline-core~=1.57.0->azureml-pipeline) (42.0.8)\nRequirement already satisfied: six>=1.11.0 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from azure-core<2.0.0->azureml-core~=1.57.0->azureml-pipeline-core~=1.57.0->azureml-pipeline) (1.16.0)\nRequirement already satisfied: typing-extensions>=4.6.0 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from azure-core<2.0.0->azureml-core~=1.57.0->azureml-pipeline-core~=1.57.0->azureml-pipeline) (4.12.2)\nRequirement already satisfied: isodate<1.0.0,>=0.6.1 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from azure-mgmt-authorization<5,>=0.40.0->azureml-core~=1.57.0->azureml-pipeline-core~=1.57.0->azureml-pipeline) (0.6.1)\nRequirement already satisfied: azure-mgmt-core<2.0.0,>=1.3.2 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from azure-mgmt-authorization<5,>=0.40.0->azureml-core~=1.57.0->azureml-pipeline-core~=1.57.0->azureml-pipeline) (1.4.0)\nRequirement already satisfied: importlib-metadata<=8.2.0 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from azureml-automl-core~=1.57.0->azureml-train-automl-client~=1.57.0->azureml-pipeline-steps~=1.57.0->azureml-pipeline) (7.1.0)\nRequirement already satisfied: importlib-resources<=6.4.0 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from azureml-automl-core~=1.57.0->azureml-train-automl-client~=1.57.0->azureml-pipeline-steps~=1.57.0->azureml-pipeline) (6.4.0)\nRequirement already satisfied: azureml-dataprep<5.2.0a,>=5.1.0a in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from azureml-dataset-runtime~=1.57.0->azureml-train-automl-client~=1.57.0->azureml-pipeline-steps~=1.57.0->azureml-pipeline) (5.1.6)\nRequirement already satisfied: pyarrow>=0.17.0 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from azureml-dataset-runtime~=1.57.0->azureml-train-automl-client~=1.57.0->azureml-pipeline-steps~=1.57.0->azureml-pipeline) (15.0.2)\nRequirement already satisfied: numpy!=1.19.3,<1.24 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from azureml-dataset-runtime~=1.57.0->azureml-train-automl-client~=1.57.0->azureml-pipeline-steps~=1.57.0->azureml-pipeline) (1.23.5)\nRequirement already satisfied: applicationinsights in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from azureml-telemetry~=1.57.0->azureml-train-automl-client~=1.57.0->azureml-pipeline-steps~=1.57.0->azureml-pipeline) (0.11.10)\nRequirement already satisfied: pygments in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from knack<0.12.0->azureml-core~=1.57.0->azureml-pipeline-core~=1.57.0->azureml-pipeline) (2.18.0)\nRequirement already satisfied: pyyaml in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from knack<0.12.0->azureml-core~=1.57.0->azureml-pipeline-core~=1.57.0->azureml-pipeline) (6.0.1)\nRequirement already satisfied: tabulate in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from knack<0.12.0->azureml-core~=1.57.0->azureml-pipeline-core~=1.57.0->azureml-pipeline) (0.9.0)\nRequirement already satisfied: portalocker<3,>=1.0 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from msal-extensions<=2.0.0,>=0.3.0->azureml-core~=1.57.0->azureml-pipeline-core~=1.57.0->azureml-pipeline) (2.8.2)\nRequirement already satisfied: certifi>=2017.4.17 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from msrest<=0.7.1,>=0.5.1->azureml-core~=1.57.0->azureml-pipeline-core~=1.57.0->azureml-pipeline) (2024.6.2)\nRequirement already satisfied: requests-oauthlib>=0.5.0 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from msrest<=0.7.1,>=0.5.1->azureml-core~=1.57.0->azureml-pipeline-core~=1.57.0->azureml-pipeline) (2.0.0)\nRequirement already satisfied: pyasn1>=0.1.1 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from ndg-httpsclient<=0.5.1->azureml-core~=1.57.0->azureml-pipeline-core~=1.57.0->azureml-pipeline) (0.6.0)\nRequirement already satisfied: bcrypt>=3.2 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from paramiko<4.0.0,>=2.0.8->azureml-core~=1.57.0->azureml-pipeline-core~=1.57.0->azureml-pipeline) (4.1.3)\nRequirement already satisfied: pynacl>=1.5 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from paramiko<4.0.0,>=2.0.8->azureml-core~=1.57.0->azureml-pipeline-core~=1.57.0->azureml-pipeline) (1.5.0)\nRequirement already satisfied: charset-normalizer<4,>=2 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from requests<3.0.0,>=2.19.1->requests[socks]<3.0.0,>=2.19.1->azureml-core~=1.57.0->azureml-pipeline-core~=1.57.0->azureml-pipeline) (3.3.2)\nRequirement already satisfied: idna<4,>=2.5 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from requests<3.0.0,>=2.19.1->requests[socks]<3.0.0,>=2.19.1->azureml-core~=1.57.0->azureml-pipeline-core~=1.57.0->azureml-pipeline) (3.7)\nRequirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from requests[socks]<3.0.0,>=2.19.1->azureml-core~=1.57.0->azureml-pipeline-core~=1.57.0->azureml-pipeline) (1.7.1)\nRequirement already satisfied: jeepney>=0.6 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from SecretStorage<4.0.0->azureml-core~=1.57.0->azureml-pipeline-core~=1.57.0->azureml-pipeline) (0.8.0)\nRequirement already satisfied: backports.weakref in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from backports.tempfile->azureml-core~=1.57.0->azureml-pipeline-core~=1.57.0->azureml-pipeline) (1.0.post1)\nRequirement already satisfied: azureml-dataprep-native<42.0.0,>=41.0.0 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from azureml-dataprep<5.2.0a,>=5.1.0a->azureml-dataset-runtime~=1.57.0->azureml-train-automl-client~=1.57.0->azureml-pipeline-steps~=1.57.0->azureml-pipeline) (41.0.0)\nRequirement already satisfied: azureml-dataprep-rslex~=2.22.2dev0 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from azureml-dataprep<5.2.0a,>=5.1.0a->azureml-dataset-runtime~=1.57.0->azureml-train-automl-client~=1.57.0->azureml-pipeline-steps~=1.57.0->azureml-pipeline) (2.22.2)\nRequirement already satisfied: cloudpickle<3.0.0,>=1.1.0 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from azureml-dataprep<5.2.0a,>=5.1.0a->azureml-dataset-runtime~=1.57.0->azureml-train-automl-client~=1.57.0->azureml-pipeline-steps~=1.57.0->azureml-pipeline) (2.2.1)\nRequirement already satisfied: azure-identity>=1.7.0 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from azureml-dataprep<5.2.0a,>=5.1.0a->azureml-dataset-runtime~=1.57.0->azureml-train-automl-client~=1.57.0->azureml-pipeline-steps~=1.57.0->azureml-pipeline) (1.16.0)\nRequirement already satisfied: jsonschema in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from azureml-dataprep<5.2.0a,>=5.1.0a->azureml-dataset-runtime~=1.57.0->azureml-train-automl-client~=1.57.0->azureml-pipeline-steps~=1.57.0->azureml-pipeline) (4.22.0)\nRequirement already satisfied: cffi>=1.12 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from cryptography>=1.1.0->adal<=1.2.7,>=1.2.0->azureml-core~=1.57.0->azureml-pipeline-core~=1.57.0->azureml-pipeline) (1.16.0)\nRequirement already satisfied: zipp>=0.5 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from importlib-metadata<=8.2.0->azureml-automl-core~=1.57.0->azureml-train-automl-client~=1.57.0->azureml-pipeline-steps~=1.57.0->azureml-pipeline) (3.19.2)\nRequirement already satisfied: oauthlib>=3.0.0 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from requests-oauthlib>=0.5.0->msrest<=0.7.1,>=0.5.1->azureml-core~=1.57.0->azureml-pipeline-core~=1.57.0->azureml-pipeline) (3.2.2)\nRequirement already satisfied: pycparser in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from cffi>=1.12->cryptography>=1.1.0->adal<=1.2.7,>=1.2.0->azureml-core~=1.57.0->azureml-pipeline-core~=1.57.0->azureml-pipeline) (2.22)\nRequirement already satisfied: attrs>=22.2.0 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from jsonschema->azureml-dataprep<5.2.0a,>=5.1.0a->azureml-dataset-runtime~=1.57.0->azureml-train-automl-client~=1.57.0->azureml-pipeline-steps~=1.57.0->azureml-pipeline) (23.2.0)\nRequirement already satisfied: jsonschema-specifications>=2023.03.6 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from jsonschema->azureml-dataprep<5.2.0a,>=5.1.0a->azureml-dataset-runtime~=1.57.0->azureml-train-automl-client~=1.57.0->azureml-pipeline-steps~=1.57.0->azureml-pipeline) (2023.12.1)\nRequirement already satisfied: referencing>=0.28.4 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from jsonschema->azureml-dataprep<5.2.0a,>=5.1.0a->azureml-dataset-runtime~=1.57.0->azureml-train-automl-client~=1.57.0->azureml-pipeline-steps~=1.57.0->azureml-pipeline) (0.35.1)\nRequirement already satisfied: rpds-py>=0.7.1 in /anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages (from jsonschema->azureml-dataprep<5.2.0a,>=5.1.0a->azureml-dataset-runtime~=1.57.0->azureml-train-automl-client~=1.57.0->azureml-pipeline-steps~=1.57.0->azureml-pipeline) (0.18.1)\nNote: you may need to restart the kernel to use updated packages.\n"
        }
      ],
      "execution_count": 3,
      "metadata": {
        "jupyter": {
          "source_hidden": false,
          "outputs_hidden": false
        },
        "nteract": {
          "transient": {
            "deleting": false
          }
        },
        "gather": {
          "logged": 1723924567905
        }
      }
    },
    {
      "cell_type": "code",
      "source": [
        "# Initialize workspace\n",
        "ws = Workspace.from_config(\"Users/mypersonall3099/Online_retail/config.json\")\n",
        "\n",
        "# Define compute target\n",
        "compute_name = \"OnlineRetail\"\n",
        "compute_target = ws.compute_targets[compute_name]"
      ],
      "outputs": [],
      "execution_count": 4,
      "metadata": {
        "jupyter": {
          "source_hidden": false,
          "outputs_hidden": false
        },
        "nteract": {
          "transient": {
            "deleting": false
          }
        },
        "gather": {
          "logged": 1723924581574
        }
      }
    },
    {
      "cell_type": "code",
      "source": [
        "#vm_size = \"Standard_E4ds_v4\"\n",
        "\n",
        "# Define environment\n",
        "env = Environment.from_conda_specification(name=\"myenv\", file_path=\"environment.yaml\")\n",
        "env.register(workspace=ws)\n"
      ],
      "outputs": [
        {
          "output_type": "execute_result",
          "execution_count": 5,
          "data": {
            "text/plain": "{\n    \"assetId\": \"azureml://locations/eastus2/workspaces/7ce76f32-f5fe-4dd3-b900-96fb92b58ebb/environments/myenv/versions/3\",\n    \"databricks\": {\n        \"eggLibraries\": [],\n        \"jarLibraries\": [],\n        \"mavenLibraries\": [],\n        \"pypiLibraries\": [],\n        \"rcranLibraries\": []\n    },\n    \"docker\": {\n        \"arguments\": [],\n        \"baseDockerfile\": null,\n        \"baseImage\": \"mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:20240709.v1\",\n        \"baseImageRegistry\": {\n            \"address\": null,\n            \"password\": null,\n            \"registryIdentity\": null,\n            \"username\": null\n        },\n        \"buildContext\": null,\n        \"enabled\": false,\n        \"platform\": {\n            \"architecture\": \"amd64\",\n            \"os\": \"Linux\"\n        },\n        \"sharedVolumes\": true,\n        \"shmSize\": null\n    },\n    \"environmentVariables\": {\n        \"EXAMPLE_ENV_VAR\": \"EXAMPLE_VALUE\"\n    },\n    \"inferencingStackVersion\": null,\n    \"name\": \"myenv\",\n    \"python\": {\n        \"baseCondaEnvironment\": null,\n        \"condaDependencies\": {\n            \"channels\": [\n                \"defaults\"\n            ],\n            \"dependencies\": [\n                \"python=3.7\",\n                \"scikit-learn\",\n                \"statsmodels\",\n                \"pip\",\n                {\n                    \"pip\": [\n                        \"pmdarima\",\n                        \"azureml-sdk\",\n                        \"azureml-dataset-runtime[fuse, pandas]\",\n                        \"joblib\",\n                        \"scikit-learn\"\n                    ]\n                }\n            ],\n            \"name\": \"myenv\"\n        },\n        \"condaDependenciesFile\": null,\n        \"interpreterPath\": \"python\",\n        \"userManagedDependencies\": false\n    },\n    \"r\": null,\n    \"spark\": {\n        \"packages\": [],\n        \"precachePackages\": true,\n        \"repositories\": []\n    },\n    \"version\": \"3\"\n}"
          },
          "metadata": {}
        }
      ],
      "execution_count": 5,
      "metadata": {
        "jupyter": {
          "source_hidden": false,
          "outputs_hidden": false
        },
        "nteract": {
          "transient": {
            "deleting": false
          }
        },
        "gather": {
          "logged": 1723924645918
        }
      }
    },
    {
      "cell_type": "code",
      "source": [
        "from azureml.core import Environment\n",
        "\n",
        "env = Environment.get(workspace=ws, name=\"myenv\")\n",
        "print(env.python.conda_dependencies.serialize_to_string())\n"
      ],
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": "name: myenv\nchannels:\n- defaults\ndependencies:\n- python=3.7\n- scikit-learn\n- statsmodels\n- pip\n- pip:\n  - pmdarima\n  - azureml-sdk\n  - azureml-dataset-runtime[fuse, pandas]\n  - joblib\n  - scikit-learn\n\n"
        }
      ],
      "execution_count": 6,
      "metadata": {
        "jupyter": {
          "source_hidden": false,
          "outputs_hidden": false
        },
        "nteract": {
          "transient": {
            "deleting": false
          }
        },
        "gather": {
          "logged": 1723924666258
        }
      }
    },
    {
      "cell_type": "code",
      "source": [
        "#Declaring environment\n",
        "# aml_config = RunConfiguration()\n",
        "# aml_config.target = compute_target \n",
        "\n",
        "# #env = Environment.from_conda_specification(name=\"myenv\", file_path=\"environment.yaml\")\n",
        "\n",
        "\n",
        "# Define run configuration\n",
        "aml_config = RunConfiguration()\n",
        "aml_config.target = compute_target\n",
        "aml_config.environment = env"
      ],
      "outputs": [],
      "execution_count": 7,
      "metadata": {
        "jupyter": {
          "source_hidden": false,
          "outputs_hidden": false
        },
        "nteract": {
          "transient": {
            "deleting": false
          }
        },
        "gather": {
          "logged": 1723924709213
        }
      }
    },
    {
      "cell_type": "code",
      "source": [
        "print(env.environment_variables)"
      ],
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": "{'EXAMPLE_ENV_VAR': 'EXAMPLE_VALUE'}\n"
        }
      ],
      "execution_count": 8,
      "metadata": {
        "jupyter": {
          "source_hidden": false,
          "outputs_hidden": false
        },
        "nteract": {
          "transient": {
            "deleting": false
          }
        },
        "gather": {
          "logged": 1723924729694
        }
      }
    },
    {
      "cell_type": "code",
      "source": [
        "try:\n",
        "    import sklearn\n",
        "    import joblib\n",
        "    print(\"scikit-learn version:\", sklearn.__version__)\n",
        "    print(\"joblib version:\", joblib.__version__)\n",
        "except ImportError as e:\n",
        "    print(f\"Import error: {e}\")\n"
      ],
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": "scikit-learn version: 1.5.0\njoblib version: 1.4.2\n"
        }
      ],
      "execution_count": 9,
      "metadata": {
        "jupyter": {
          "source_hidden": false,
          "outputs_hidden": false
        },
        "nteract": {
          "transient": {
            "deleting": false
          }
        },
        "gather": {
          "logged": 1723924733025
        }
      }
    },
    {
      "cell_type": "code",
      "source": [
        "# #Pipeline\n",
        "# read_data = 'data_wrangling.py'\n",
        "# prep = 'preprocessing.py'\n",
        "# model = 'modelling.py'\n",
        "\n",
        "# #Script initialization\n",
        "# py_script_run_read = PythonScriptStep(\n",
        "#                 script_name = read_data,\n",
        "#                 compute_target = compute_target,\n",
        "#                 arguments=['--input-data','online_retail_II.csv'],\n",
        "#                 runconfig = aml_config,\n",
        "#                 allow_reuse=False)\n",
        "\n",
        "# py_script_run_prep = PythonScriptStep(\n",
        "#                 script_name = prep,\n",
        "#                 compute_target=compute_target,\n",
        "#                 arguments=['--prep','wranggled.csv'],\n",
        "#                 runconfig = aml_config,\n",
        "#                 allow_reuse=False)\n",
        "\n",
        "# # py_script_run_model = PythonScriptStep(\n",
        "# #                 script_name = model,\n",
        "#                 compute_target=compute_target,\n",
        "#                 arguments=['--train','preprocessed.csv'],\n",
        "#                 runconfig = aml_config,\n",
        "#                 allow_reuse=False)\n",
        "\n",
        "# pipeline_steps = [py_script_run_read, py_script_run_prep, py_script_run_model]\n",
        "# pipeline_1 = Pipeline(workspace=ws, steps = pipeline_steps)"
      ],
      "outputs": [],
      "execution_count": 98,
      "metadata": {
        "jupyter": {
          "source_hidden": false,
          "outputs_hidden": false
        },
        "nteract": {
          "transient": {
            "deleting": false
          }
        },
        "gather": {
          "logged": 1723914145399
        }
      }
    },
    {
      "cell_type": "code",
      "source": [
        "# Define pipeline steps\n",
        "read_data = 'data_wrangling.py'\n",
        "prep = 'preprocessing.py'\n",
        "model = 'modelling.py'\n",
        "\n",
        "py_script_run_read = PythonScriptStep(\n",
        "    script_name=read_data,\n",
        "    compute_target=compute_target,\n",
        "    arguments=['--input-data', 'online_retail_II.csv'],\n",
        "    runconfig=aml_config,\n",
        "    allow_reuse=False\n",
        ")\n",
        "\n",
        "py_script_run_prep = PythonScriptStep(\n",
        "    script_name=prep,\n",
        "    compute_target=compute_target,\n",
        "    arguments=['--prep', 'wrangled.csv'],\n",
        "    runconfig=aml_config,\n",
        "    allow_reuse=False\n",
        ")\n",
        "\n",
        "py_script_run_model = PythonScriptStep(\n",
        "    script_name=model,\n",
        "    compute_target=compute_target,\n",
        "    arguments=['--train', 'preprocessed.csv'],\n",
        "    runconfig=aml_config,\n",
        "    allow_reuse=False\n",
        ")\n",
        "\n",
        "# Create and submit pipeline\n",
        "pipeline_steps = [py_script_run_read, py_script_run_prep, py_script_run_model]\n",
        "pipeline = Pipeline(workspace=ws, steps=pipeline_steps)\n"
      ],
      "outputs": [],
      "execution_count": 10,
      "metadata": {
        "jupyter": {
          "source_hidden": false,
          "outputs_hidden": false
        },
        "nteract": {
          "transient": {
            "deleting": false
          }
        },
        "gather": {
          "logged": 1723924780872
        }
      }
    },
    {
      "cell_type": "code",
      "source": [
        "# Experiment\n",
        "\n",
        "# pipeline_run = Experiment(ws, \"First_run_7\").submit(pipeline_1)\n",
        "# pipeline_run.wait_for_completion(show_output=True)\n",
        "\n",
        "experiment_name = \"Run1\"\n",
        "experiment = Experiment(ws, experiment_name)\n",
        "pipeline_run = experiment.submit(pipeline)\n",
        "pipeline_run.wait_for_completion(show_output=True)"
      ],
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": "Submitted PipelineRun 62d5bd6a-9a58-47a9-bf9e-913a99769d5f\nLink to Azure Machine Learning Portal: https://ml.azure.com/runs/62d5bd6a-9a58-47a9-bf9e-913a99769d5f?wsid=/subscriptions/d8c4fe8f-f720-48ac-86e8-880576d9cd7a/resourcegroups/OnlineRetail/workspaces/OnlineRetail&tid=f56f1f69-458e-427b-bada-4cba658f7917\nPipelineRunId: 62d5bd6a-9a58-47a9-bf9e-913a99769d5f\nLink to Azure Machine Learning Portal: https://ml.azure.com/runs/62d5bd6a-9a58-47a9-bf9e-913a99769d5f?wsid=/subscriptions/d8c4fe8f-f720-48ac-86e8-880576d9cd7a/resourcegroups/OnlineRetail/workspaces/OnlineRetail&tid=f56f1f69-458e-427b-bada-4cba658f7917\nPipelineRun Status: NotStarted\nPipelineRun Status: Running\n\n\nStepRunId: 48897db4-60a6-491d-8fc0-472c4fc819af\nLink to Azure Machine Learning Portal: https://ml.azure.com/runs/48897db4-60a6-491d-8fc0-472c4fc819af?wsid=/subscriptions/d8c4fe8f-f720-48ac-86e8-880576d9cd7a/resourcegroups/OnlineRetail/workspaces/OnlineRetail&tid=f56f1f69-458e-427b-bada-4cba658f7917\nStepRun( preprocessing.py ) Status: NotStarted\n\nStepRun(preprocessing.py) Execution Summary\n============================================\nStepRun( preprocessing.py ) Status: Canceled\n{'runId': '48897db4-60a6-491d-8fc0-472c4fc819af', 'target': 'OnlineRetail', 'status': 'Running', 'startTimeUtc': '2024-08-17T20:13:35.82727Z', 'services': {}, 'properties': {'ContentSnapshotId': 'cffc586e-7af5-43a5-bca0-a24682dcf872', 'StepType': 'PythonScriptStep', 'azureml.moduleid': '249f17cd-cf83-4e52-be21-5c56d6264151', 'azureml.moduleFamilyId': '85bb4fdc-8107-4c51-9bed-08823aa32e30', 'azureml.moduleName': 'preprocessing.py', 'azureml.runsource': 'azureml.StepRun', 'azureml.nodeid': 'f75cdf2b', 'azureml.pipelinerunid': '62d5bd6a-9a58-47a9-bf9e-913a99769d5f', 'azureml.pipeline': '62d5bd6a-9a58-47a9-bf9e-913a99769d5f', 'azureml.rootpipelinerunid': '62d5bd6a-9a58-47a9-bf9e-913a99769d5f', 'azureml.pipelineComponent': 'masterescloud', '_azureml.ComputeTargetType': 'amlcdsi', '_azureml.ClusterName': 'OnlineRetail', 'ProcessInfoFile': 'azureml-logs/process_info.json', 'ProcessStatusFile': 'azureml-logs/process_status.json'}, 'inputDatasets': [], 'outputDatasets': [], 'runDefinition': {'script': 'preprocessing.py', 'command': '', 'useAbsolutePath': False, 'arguments': ['--prep', 'wrangled.csv'], 'sourceDirectoryDataStore': None, 'framework': 'Python', 'communicator': 'None', 'target': 'OnlineRetail', 'dataReferences': {}, 'data': {}, 'outputData': {}, 'datacaches': [], 'jobName': None, 'maxRunDurationSeconds': None, 'nodeCount': 1, 'instanceTypes': [], 'priority': None, 'credentialPassthrough': False, 'identity': None, 'environment': {'name': 'myenv', 'version': '3', 'assetId': 'azureml://locations/eastus2/workspaces/7ce76f32-f5fe-4dd3-b900-96fb92b58ebb/environments/myenv/versions/3', 'autoRebuild': True, 'python': {'interpreterPath': 'python', 'userManagedDependencies': False, 'condaDependencies': {'name': 'myenv', 'channels': ['defaults'], 'dependencies': ['python=3.7', 'scikit-learn', 'statsmodels', 'pip', {'pip': ['pmdarima', 'azureml-sdk', 'azureml-dataset-runtime[fuse, pandas]', 'joblib', 'scikit-learn']}]}, 'baseCondaEnvironment': None}, 'environmentVariables': {'EXAMPLE_ENV_VAR': 'EXAMPLE_VALUE'}, 'docker': {'baseImage': 'mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu20.04:20240709.v1', 'platform': {'os': 'Linux', 'architecture': 'amd64'}, 'baseDockerfile': None, 'baseImageRegistry': {'address': None, 'username': None, 'password': None}, 'enabled': False, 'arguments': []}, 'spark': {'repositories': [], 'packages': [], 'precachePackages': True}, 'inferencingStackVersion': None}, 'history': {'outputCollection': True, 'directoriesToWatch': ['logs'], 'enableMLflowTracking': True, 'snapshotProject': True}, 'spark': {'configuration': {'spark.app.name': 'Azure ML Experiment', 'spark.yarn.maxAppAttempts': '1'}}, 'parallelTask': {'maxRetriesPerWorker': 0, 'workerCountPerNode': 1, 'terminalExitCodes': None, 'configuration': {}}, 'amlCompute': {'name': None, 'vmSize': None, 'retainCluster': False, 'clusterMaxNodeCount': 1}, 'aiSuperComputer': {'instanceType': 'D2', 'imageVersion': 'pytorch-1.7.0', 'location': None, 'aiSuperComputerStorageData': None, 'interactive': False, 'scalePolicy': None, 'virtualClusterArmId': None, 'tensorboardLogDirectory': None, 'sshPublicKey': None, 'sshPublicKeys': None, 'enableAzmlInt': True, 'priority': 'Medium', 'slaTier': 'Standard', 'userAlias': None}, 'kubernetesCompute': {'instanceType': None}, 'tensorflow': {'workerCount': 1, 'parameterServerCount': 1}, 'mpi': {'processCountPerNode': 1}, 'pyTorch': {'communicationBackend': 'nccl', 'processCount': None}, 'hdi': {'yarnDeployMode': 'Cluster'}, 'containerInstance': {'region': None, 'cpuCores': 2.0, 'memoryGb': 3.5}, 'exposedPorts': None, 'docker': {'useDocker': False, 'sharedVolumes': True, 'shmSize': '2g', 'arguments': []}, 'cmk8sCompute': {'configuration': {}}, 'commandReturnCodeConfig': {'returnCode': 'Zero', 'successfulReturnCodes': []}, 'environmentVariables': {}, 'applicationEndpoints': {}, 'parameters': []}, 'logFiles': {'logs/azureml/executionlogs.txt': 'https://onlineretail3582987100.blob.core.windows.net/azureml/ExperimentRun/dcid.48897db4-60a6-491d-8fc0-472c4fc819af/logs/azureml/executionlogs.txt?sv=2019-07-07&sr=b&sig=7A4NgPUTlLTWnlv%2FL7l1snPm0TXfBMuPULWFuc6RC10%3D&skoid=71b8eb28-71de-44ad-919a-150ed222a16f&sktid=f56f1f69-458e-427b-bada-4cba658f7917&skt=2024-08-17T20%3A01%3A00Z&ske=2024-08-18T20%3A11%3A00Z&sks=b&skv=2019-07-07&st=2024-08-17T20%3A03%3A15Z&se=2024-08-18T04%3A13%3A15Z&sp=r', 'logs/azureml/stderrlogs.txt': 'https://onlineretail3582987100.blob.core.windows.net/azureml/ExperimentRun/dcid.48897db4-60a6-491d-8fc0-472c4fc819af/logs/azureml/stderrlogs.txt?sv=2019-07-07&sr=b&sig=x7mGVWUzV2gp9cWtzFhCliol8LzFFIHuMIy8taNcYK8%3D&skoid=71b8eb28-71de-44ad-919a-150ed222a16f&sktid=f56f1f69-458e-427b-bada-4cba658f7917&skt=2024-08-17T20%3A01%3A00Z&ske=2024-08-18T20%3A11%3A00Z&sks=b&skv=2019-07-07&st=2024-08-17T20%3A03%3A15Z&se=2024-08-18T04%3A13%3A15Z&sp=r', 'logs/azureml/stdoutlogs.txt': 'https://onlineretail3582987100.blob.core.windows.net/azureml/ExperimentRun/dcid.48897db4-60a6-491d-8fc0-472c4fc819af/logs/azureml/stdoutlogs.txt?sv=2019-07-07&sr=b&sig=J3WSccoOFWwgyVDptDGEP1vJqJEFjlMj18qFDSN2oiw%3D&skoid=71b8eb28-71de-44ad-919a-150ed222a16f&sktid=f56f1f69-458e-427b-bada-4cba658f7917&skt=2024-08-17T20%3A01%3A00Z&ske=2024-08-18T20%3A11%3A00Z&sks=b&skv=2019-07-07&st=2024-08-17T20%3A03%3A15Z&se=2024-08-18T04%3A13%3A15Z&sp=r'}, 'submittedBy': 'Divya Jain'}\n\n\n\n\nStepRunId: 5e97c52f-c123-4d27-880a-e222433680d8\nLink to Azure Machine Learning Portal: https://ml.azure.com/runs/5e97c52f-c123-4d27-880a-e222433680d8?wsid=/subscriptions/d8c4fe8f-f720-48ac-86e8-880576d9cd7a/resourcegroups/OnlineRetail/workspaces/OnlineRetail&tid=f56f1f69-458e-427b-bada-4cba658f7917\n\nStepRun(data_wrangling.py) Execution Summary\n=============================================\nStepRun( data_wrangling.py ) Status: Failed\n\nWarnings:\nExecution failed. User process '/azureml-envs/azureml_366da3323363019eaa2f3dfe7d52dbd9/bin/python' exited with status code 1. Please check log file 'user_logs/std_log.txt' for error details. Error:   File \"/azureml-envs/azureml_366da3323363019eaa2f3dfe7d52dbd9/lib/python3.7/site-packages/azureml/data/_loggerfactory.py\", line 140, in wrapper\n    return func(*args, **kwargs)\n  File \"/azureml-envs/azureml_366da3323363019eaa2f3dfe7d52dbd9/lib/python3.7/site-packages/azureml/data/dataset_factory.py\",\nExecution failed. User process '/azureml-envs/azureml_366da3323363019eaa2f3dfe7d52dbd9/bin/python' exited with status code 1. Please check log file 'user_logs/std_log.txt' for error details. Error:   File \"/azureml-envs/azureml_366da3323363019eaa2f3dfe7d52dbd9/lib/python3.7/site-packages/azureml/data/_loggerfactory.py\", line 140, in wrapper\n    return func(*args, **kwargs)\n  File \"/azureml-envs/azureml_366da3323363019eaa2f3dfe7d52dbd9/lib/python3.7/site-packages/azureml/data/dataset_factory.py\",\n"
        },
        {
          "output_type": "error",
          "ename": "ActivityFailedException",
          "evalue": "ActivityFailedException:\n\tMessage: Activity Failed:\n{\n    \"error\": {\n        \"code\": \"UserError\",\n        \"message\": \"Execution failed. User process '/azureml-envs/azureml_366da3323363019eaa2f3dfe7d52dbd9/bin/python' exited with status code 1. Please check log file 'user_logs/std_log.txt' for error details. Error:   File \\\"/azureml-envs/azureml_366da3323363019eaa2f3dfe7d52dbd9/lib/python3.7/site-packages/azureml/data/_loggerfactory.py\\\", line 140, in wrapper\\n    return func(*args, **kwargs)\\n  File \\\"/azureml-envs/azureml_366da3323363019eaa2f3dfe7d52dbd9/lib/python3.7/site-packages/azureml/data/dataset_factory.py\\\", line 354, in from_delimited_files\\n    infer_column_types=infer_column_types or _is_inference_required(set_column_types, validate))\\n  File \\\"/azureml-envs/azureml_366da3323363019eaa2f3dfe7d52dbd9/lib/python3.7/site-packages/azureml/data/dataset_factory.py\\\", line 1189, in _transform_and_validate\\n    _validate_has_data(dataflow, 'Failed to validate the data.'\\n  File \\\"/azureml-envs/azureml_366da3323363019eaa2f3dfe7d52dbd9/lib/python3.7/site-packages/azureml/data/dataset_error_handling.py\\\", line 69, in _validate_has_data\\n    raise DatasetValidationError(error_message + '\\\\n' + e.compliant_message, exception=e)\\nazureml.data.dataset_error_handling.DatasetValidationError: DatasetValidationError:\\n\\tMessage: Failed to validate the data.If data is inaccessible, please set validate to False.\\nThe requested stream was not found. Please make sure the request uri is correct.| session_id=d5ae4b03-2b70-49e9-a694-934511f4abf4\\n\\tInnerException None\\n\\tErrorResponse \\n{\\n    \\\"error\\\": {\\n        \\\"code\\\": \\\"UserError\\\",\\n        \\\"message\\\": \\\"Failed to validate the data.If data is inaccessible, please set validate to False.\\\\nThe requested stream was not found. Please make sure the request uri is correct.| session_id=d5ae4b03-2b70-49e9-a694-934511f4abf4\\\"\\n    }\\n}\\n\\n\",\n        \"messageParameters\": {},\n        \"details\": []\n    },\n    \"time\": \"0001-01-01T00:00:00.000Z\",\n    \"componentName\": \"CommonRuntime\"\n}\n\tInnerException None\n\tErrorResponse \n{\n    \"error\": {\n        \"message\": \"Activity Failed:\\n{\\n    \\\"error\\\": {\\n        \\\"code\\\": \\\"UserError\\\",\\n        \\\"message\\\": \\\"Execution failed. User process '/azureml-envs/azureml_366da3323363019eaa2f3dfe7d52dbd9/bin/python' exited with status code 1. Please check log file 'user_logs/std_log.txt' for error details. Error:   File \\\\\\\"/azureml-envs/azureml_366da3323363019eaa2f3dfe7d52dbd9/lib/python3.7/site-packages/azureml/data/_loggerfactory.py\\\\\\\", line 140, in wrapper\\\\n    return func(*args, **kwargs)\\\\n  File \\\\\\\"/azureml-envs/azureml_366da3323363019eaa2f3dfe7d52dbd9/lib/python3.7/site-packages/azureml/data/dataset_factory.py\\\\\\\", line 354, in from_delimited_files\\\\n    infer_column_types=infer_column_types or _is_inference_required(set_column_types, validate))\\\\n  File \\\\\\\"/azureml-envs/azureml_366da3323363019eaa2f3dfe7d52dbd9/lib/python3.7/site-packages/azureml/data/dataset_factory.py\\\\\\\", line 1189, in _transform_and_validate\\\\n    _validate_has_data(dataflow, 'Failed to validate the data.'\\\\n  File \\\\\\\"/azureml-envs/azureml_366da3323363019eaa2f3dfe7d52dbd9/lib/python3.7/site-packages/azureml/data/dataset_error_handling.py\\\\\\\", line 69, in _validate_has_data\\\\n    raise DatasetValidationError(error_message + '\\\\\\\\n' + e.compliant_message, exception=e)\\\\nazureml.data.dataset_error_handling.DatasetValidationError: DatasetValidationError:\\\\n\\\\tMessage: Failed to validate the data.If data is inaccessible, please set validate to False.\\\\nThe requested stream was not found. Please make sure the request uri is correct.| session_id=d5ae4b03-2b70-49e9-a694-934511f4abf4\\\\n\\\\tInnerException None\\\\n\\\\tErrorResponse \\\\n{\\\\n    \\\\\\\"error\\\\\\\": {\\\\n        \\\\\\\"code\\\\\\\": \\\\\\\"UserError\\\\\\\",\\\\n        \\\\\\\"message\\\\\\\": \\\\\\\"Failed to validate the data.If data is inaccessible, please set validate to False.\\\\\\\\nThe requested stream was not found. Please make sure the request uri is correct.| session_id=d5ae4b03-2b70-49e9-a694-934511f4abf4\\\\\\\"\\\\n    }\\\\n}\\\\n\\\\n\\\",\\n        \\\"messageParameters\\\": {},\\n        \\\"details\\\": []\\n    },\\n    \\\"time\\\": \\\"0001-01-01T00:00:00.000Z\\\",\\n    \\\"componentName\\\": \\\"CommonRuntime\\\"\\n}\"\n    }\n}",
          "traceback": [
            "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
            "\u001b[0;31mActivityFailedException\u001b[0m                   Traceback (most recent call last)",
            "Cell \u001b[0;32mIn[12], line 9\u001b[0m\n\u001b[1;32m      7\u001b[0m experiment \u001b[38;5;241m=\u001b[39m Experiment(ws, experiment_name)\n\u001b[1;32m      8\u001b[0m pipeline_run \u001b[38;5;241m=\u001b[39m experiment\u001b[38;5;241m.\u001b[39msubmit(pipeline)\n\u001b[0;32m----> 9\u001b[0m \u001b[43mpipeline_run\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mwait_for_completion\u001b[49m\u001b[43m(\u001b[49m\u001b[43mshow_output\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;28;43;01mTrue\u001b[39;49;00m\u001b[43m)\u001b[49m\n",
            "File \u001b[0;32m/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/azureml/pipeline/core/run.py:295\u001b[0m, in \u001b[0;36mPipelineRun.wait_for_completion\u001b[0;34m(self, show_output, timeout_seconds, raise_on_error)\u001b[0m\n\u001b[1;32m    293\u001b[0m \u001b[38;5;28mprint\u001b[39m(\u001b[38;5;124m'\u001b[39m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;124m'\u001b[39m)\n\u001b[1;32m    294\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[0;32m--> 295\u001b[0m     \u001b[43mstep_run\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mwait_for_completion\u001b[49m\u001b[43m(\u001b[49m\u001b[43mtimeout_seconds\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mtimeout_seconds\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m-\u001b[39;49m\u001b[43m \u001b[49m\u001b[43mtime_elapsed\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    296\u001b[0m \u001b[43m                                 \u001b[49m\u001b[43mraise_on_error\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mraise_on_error\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    297\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mTypeError\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[1;32m    298\u001b[0m     \u001b[38;5;66;03m# If there are package conflicts in the user's environment, the run rehydration\u001b[39;00m\n\u001b[1;32m    299\u001b[0m     \u001b[38;5;66;03m# will not work and we will receive a Run object instead of StepRun.\u001b[39;00m\n\u001b[1;32m    300\u001b[0m     \u001b[38;5;66;03m# Run.wait_for_completion() does not have a parameter timeout_seconds, which\u001b[39;00m\n\u001b[1;32m    301\u001b[0m     \u001b[38;5;66;03m# will generate a TypeError here.  As a workaround, call the method without\u001b[39;00m\n\u001b[1;32m    302\u001b[0m     \u001b[38;5;66;03m# this parameter.\u001b[39;00m\n\u001b[1;32m    303\u001b[0m     \u001b[38;5;28;01mif\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28misinstance\u001b[39m(step_run, StepRun):\n",
            "File \u001b[0;32m/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/azureml/pipeline/core/run.py:742\u001b[0m, in \u001b[0;36mStepRun.wait_for_completion\u001b[0;34m(self, show_output, timeout_seconds, raise_on_error)\u001b[0m\n\u001b[1;32m    740\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m show_output:\n\u001b[1;32m    741\u001b[0m     \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[0;32m--> 742\u001b[0m         \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[38;5;28;43mself\u001b[39;49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43m_stream_run_output\u001b[49m\u001b[43m(\u001b[49m\u001b[43mtimeout_seconds\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mtimeout_seconds\u001b[49m\u001b[43m,\u001b[49m\n\u001b[1;32m    743\u001b[0m \u001b[43m                                       \u001b[49m\u001b[43mraise_on_error\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43mraise_on_error\u001b[49m\u001b[43m)\u001b[49m\n\u001b[1;32m    744\u001b[0m     \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mKeyboardInterrupt\u001b[39;00m:\n\u001b[1;32m    745\u001b[0m         error_message \u001b[38;5;241m=\u001b[39m \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mThe output streaming for the run interrupted.\u001b[39m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;124m\"\u001b[39m \\\n\u001b[1;32m    746\u001b[0m                         \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mBut the run is still executing on the compute target. \u001b[39m\u001b[38;5;130;01m\\n\u001b[39;00m\u001b[38;5;124m\"\u001b[39m \\\n\u001b[1;32m    747\u001b[0m                         \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mDetails for canceling the run can be found here: \u001b[39m\u001b[38;5;124m\"\u001b[39m \\\n\u001b[1;32m    748\u001b[0m                         \u001b[38;5;124m\"\u001b[39m\u001b[38;5;124mhttps://aka.ms/aml-docs-cancel-run\u001b[39m\u001b[38;5;124m\"\u001b[39m\n",
            "File \u001b[0;32m/anaconda/envs/azureml_py310_sdkv2/lib/python3.10/site-packages/azureml/pipeline/core/run.py:835\u001b[0m, in \u001b[0;36mStepRun._stream_run_output\u001b[0;34m(self, timeout_seconds, raise_on_error)\u001b[0m\n\u001b[1;32m    833\u001b[0m     \u001b[38;5;28mprint\u001b[39m(json\u001b[38;5;241m.\u001b[39mdumps(error, indent\u001b[38;5;241m=\u001b[39m\u001b[38;5;241m4\u001b[39m))\n\u001b[1;32m    834\u001b[0m \u001b[38;5;28;01mif\u001b[39;00m error \u001b[38;5;129;01mand\u001b[39;00m raise_on_error:\n\u001b[0;32m--> 835\u001b[0m     \u001b[38;5;28;01mraise\u001b[39;00m ActivityFailedException(error_details\u001b[38;5;241m=\u001b[39mjson\u001b[38;5;241m.\u001b[39mdumps(error, indent\u001b[38;5;241m=\u001b[39m\u001b[38;5;241m4\u001b[39m))\n\u001b[1;32m    837\u001b[0m \u001b[38;5;28mprint\u001b[39m(final_details)\n\u001b[1;32m    838\u001b[0m \u001b[38;5;28mprint\u001b[39m(\u001b[38;5;124m'\u001b[39m\u001b[38;5;124m'\u001b[39m, flush\u001b[38;5;241m=\u001b[39m\u001b[38;5;28;01mTrue\u001b[39;00m)\n",
            "\u001b[0;31mActivityFailedException\u001b[0m: ActivityFailedException:\n\tMessage: Activity Failed:\n{\n    \"error\": {\n        \"code\": \"UserError\",\n        \"message\": \"Execution failed. User process '/azureml-envs/azureml_366da3323363019eaa2f3dfe7d52dbd9/bin/python' exited with status code 1. Please check log file 'user_logs/std_log.txt' for error details. Error:   File \\\"/azureml-envs/azureml_366da3323363019eaa2f3dfe7d52dbd9/lib/python3.7/site-packages/azureml/data/_loggerfactory.py\\\", line 140, in wrapper\\n    return func(*args, **kwargs)\\n  File \\\"/azureml-envs/azureml_366da3323363019eaa2f3dfe7d52dbd9/lib/python3.7/site-packages/azureml/data/dataset_factory.py\\\", line 354, in from_delimited_files\\n    infer_column_types=infer_column_types or _is_inference_required(set_column_types, validate))\\n  File \\\"/azureml-envs/azureml_366da3323363019eaa2f3dfe7d52dbd9/lib/python3.7/site-packages/azureml/data/dataset_factory.py\\\", line 1189, in _transform_and_validate\\n    _validate_has_data(dataflow, 'Failed to validate the data.'\\n  File \\\"/azureml-envs/azureml_366da3323363019eaa2f3dfe7d52dbd9/lib/python3.7/site-packages/azureml/data/dataset_error_handling.py\\\", line 69, in _validate_has_data\\n    raise DatasetValidationError(error_message + '\\\\n' + e.compliant_message, exception=e)\\nazureml.data.dataset_error_handling.DatasetValidationError: DatasetValidationError:\\n\\tMessage: Failed to validate the data.If data is inaccessible, please set validate to False.\\nThe requested stream was not found. Please make sure the request uri is correct.| session_id=d5ae4b03-2b70-49e9-a694-934511f4abf4\\n\\tInnerException None\\n\\tErrorResponse \\n{\\n    \\\"error\\\": {\\n        \\\"code\\\": \\\"UserError\\\",\\n        \\\"message\\\": \\\"Failed to validate the data.If data is inaccessible, please set validate to False.\\\\nThe requested stream was not found. Please make sure the request uri is correct.| session_id=d5ae4b03-2b70-49e9-a694-934511f4abf4\\\"\\n    }\\n}\\n\\n\",\n        \"messageParameters\": {},\n        \"details\": []\n    },\n    \"time\": \"0001-01-01T00:00:00.000Z\",\n    \"componentName\": \"CommonRuntime\"\n}\n\tInnerException None\n\tErrorResponse \n{\n    \"error\": {\n        \"message\": \"Activity Failed:\\n{\\n    \\\"error\\\": {\\n        \\\"code\\\": \\\"UserError\\\",\\n        \\\"message\\\": \\\"Execution failed. User process '/azureml-envs/azureml_366da3323363019eaa2f3dfe7d52dbd9/bin/python' exited with status code 1. Please check log file 'user_logs/std_log.txt' for error details. Error:   File \\\\\\\"/azureml-envs/azureml_366da3323363019eaa2f3dfe7d52dbd9/lib/python3.7/site-packages/azureml/data/_loggerfactory.py\\\\\\\", line 140, in wrapper\\\\n    return func(*args, **kwargs)\\\\n  File \\\\\\\"/azureml-envs/azureml_366da3323363019eaa2f3dfe7d52dbd9/lib/python3.7/site-packages/azureml/data/dataset_factory.py\\\\\\\", line 354, in from_delimited_files\\\\n    infer_column_types=infer_column_types or _is_inference_required(set_column_types, validate))\\\\n  File \\\\\\\"/azureml-envs/azureml_366da3323363019eaa2f3dfe7d52dbd9/lib/python3.7/site-packages/azureml/data/dataset_factory.py\\\\\\\", line 1189, in _transform_and_validate\\\\n    _validate_has_data(dataflow, 'Failed to validate the data.'\\\\n  File \\\\\\\"/azureml-envs/azureml_366da3323363019eaa2f3dfe7d52dbd9/lib/python3.7/site-packages/azureml/data/dataset_error_handling.py\\\\\\\", line 69, in _validate_has_data\\\\n    raise DatasetValidationError(error_message + '\\\\\\\\n' + e.compliant_message, exception=e)\\\\nazureml.data.dataset_error_handling.DatasetValidationError: DatasetValidationError:\\\\n\\\\tMessage: Failed to validate the data.If data is inaccessible, please set validate to False.\\\\nThe requested stream was not found. Please make sure the request uri is correct.| session_id=d5ae4b03-2b70-49e9-a694-934511f4abf4\\\\n\\\\tInnerException None\\\\n\\\\tErrorResponse \\\\n{\\\\n    \\\\\\\"error\\\\\\\": {\\\\n        \\\\\\\"code\\\\\\\": \\\\\\\"UserError\\\\\\\",\\\\n        \\\\\\\"message\\\\\\\": \\\\\\\"Failed to validate the data.If data is inaccessible, please set validate to False.\\\\\\\\nThe requested stream was not found. Please make sure the request uri is correct.| session_id=d5ae4b03-2b70-49e9-a694-934511f4abf4\\\\\\\"\\\\n    }\\\\n}\\\\n\\\\n\\\",\\n        \\\"messageParameters\\\": {},\\n        \\\"details\\\": []\\n    },\\n    \\\"time\\\": \\\"0001-01-01T00:00:00.000Z\\\",\\n    \\\"componentName\\\": \\\"CommonRuntime\\\"\\n}\"\n    }\n}"
          ]
        }
      ],
      "execution_count": 12,
      "metadata": {
        "jupyter": {
          "source_hidden": false,
          "outputs_hidden": false
        },
        "nteract": {
          "transient": {
            "deleting": false
          }
        },
        "gather": {
          "logged": 1723925617699
        }
      }
    },
    {
      "cell_type": "code",
      "source": [
        "# Experiment 2\n",
        "\n",
        "pipeline_run = Experiment(ws, \"Second_run\").submit(pipeline)\n",
        "pipeline_run.wait_for_completion(show_output=True)"
      ],
      "outputs": [],
      "execution_count": null,
      "metadata": {
        "jupyter": {
          "source_hidden": false,
          "outputs_hidden": false
        },
        "nteract": {
          "transient": {
            "deleting": false
          }
        }
      }
    },
    {
      "cell_type": "code",
      "source": [
        "from azureml.core import Workspace, Datastore\n",
        "\n",
        "# Connect to the workspace\n",
        "ws = Workspace.from_config()\n",
        "\n",
        "# Get the datastore\n",
        "datastore = Datastore.get(ws, 'workspaceblobstore')\n",
        "\n",
        "# Print details\n",
        "print(\"Datastore:\", datastore.name)\n",
        "print(\"Blob Container Name:\", datastore.container_name)\n",
        "print(\"Storage Account Name:\", datastore.account_name)\n"
      ],
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": "Datastore: workspaceblobstore\nBlob Container Name: azureml-blobstore-7ce76f32-f5fe-4dd3-b900-96fb92b58ebb\nStorage Account Name: onlineretail3582987100\n"
        }
      ],
      "execution_count": 1,
      "metadata": {
        "jupyter": {
          "source_hidden": false,
          "outputs_hidden": false
        },
        "nteract": {
          "transient": {
            "deleting": false
          }
        },
        "gather": {
          "logged": 1723923358797
        }
      }
    },
    {
      "cell_type": "code",
      "source": [
        "from azureml.core import Workspace, Datastore, Dataset\n",
        "import pandas as pd\n",
        "\n",
        "\n",
        "data_store_name = 'workspaceblobstore'\n",
        "container_name = 'azureml-blobstore-7ce76f32-f5fe-4dd3-b900-96fb92b58ebb'\n",
        "raw_data_file_path = 'online_retail_II.csv' \n",
        "\n",
        "datastore = Datastore.get(ws, data_store_name)\n",
        "dataset = Dataset.Tabular.from_delimited_files(path=[(datastore, raw_data_file_path)], validate=False)\n",
        "df = dataset.to_pandas_dataframe()\n",
        "#df = pd.read_csv(raw_data_file_path, encoding='latin1')\n",
        "\n"
      ],
      "outputs": [],
      "execution_count": 21,
      "metadata": {
        "jupyter": {
          "source_hidden": false,
          "outputs_hidden": false
        },
        "nteract": {
          "transient": {
            "deleting": false
          }
        },
        "gather": {
          "logged": 1723926098206
        }
      }
    },
    {
      "cell_type": "code",
      "source": [],
      "outputs": [],
      "execution_count": null,
      "metadata": {
        "jupyter": {
          "source_hidden": false,
          "outputs_hidden": false
        },
        "nteract": {
          "transient": {
            "deleting": false
          }
        }
      }
    }
  ],
  "metadata": {
    "kernelspec": {
      "name": "python310-sdkv2",
      "language": "python",
      "display_name": "Python 3.10 - SDK v2"
    },
    "language_info": {
      "name": "python",
      "version": "3.10.14",
      "mimetype": "text/x-python",
      "codemirror_mode": {
        "name": "ipython",
        "version": 3
      },
      "pygments_lexer": "ipython3",
      "nbconvert_exporter": "python",
      "file_extension": ".py"
    },
    "microsoft": {
      "ms_spell_check": {
        "ms_spell_check_language": "en"
      },
      "host": {
        "AzureML": {
          "notebookHasBeenCompleted": true
        }
      }
    },
    "kernel_info": {
      "name": "python310-sdkv2"
    },
    "nteract": {
      "version": "nteract-front-end@1.0.0"
    }
  },
  "nbformat": 4,
  "nbformat_minor": 2
}